services:
  frontend:
    container_name: rubiks_frontend
    build: ./frontend
    environment:
      REACT_APP_RI_BACKEND_URL: ${REACT_APP_RI_BACKEND_URL}
    ports:
      - 3000:3000
    
  backend:
    container_name: rubiks_backend
    build: ./backend
    environment:
      RI_BACKEND_PORT: "${RI_BACKEND_PORT}"
    ports:
      - 8150:8150